import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import test from "node:test";

test("standalone strong stock workbench is wired without daily-report modules", () => {
  const typesSource = readFileSync(new URL("./types.ts", import.meta.url), "utf8");
  const apiSource = readFileSync(new URL("./api.ts", import.meta.url), "utf8");
  const componentSource = readFileSync(new URL("../components/ScreenerWorkbench.tsx", import.meta.url), "utf8");
  const pageSource = readFileSync(new URL("../app/page.tsx", import.meta.url), "utf8");
  const layoutSource = readFileSync(new URL("../app/layout.tsx", import.meta.url), "utf8");
  const antdProviderSource = readFileSync(new URL("../components/AntdAppProvider.tsx", import.meta.url), "utf8");
  const watchlistPageSource = readFileSync(new URL("../app/watchlist/page.tsx", import.meta.url), "utf8");
  const stockPageUrl = new URL("../app/stock/[symbol]/page.tsx", import.meta.url);
  const stockPageSource = existsSync(stockPageUrl) ? readFileSync(stockPageUrl, "utf8") : "";
  const stockChartSource = readFileSync(new URL("../components/TickFlowKlineChart.tsx", import.meta.url), "utf8");
  const settingsPageSource = readFileSync(new URL("../app/settings/page.tsx", import.meta.url), "utf8");
  const sectorsPageUrl = new URL("../app/sectors/page.tsx", import.meta.url);
  const sectorsPageSource = existsSync(sectorsPageUrl) ? readFileSync(sectorsPageUrl, "utf8") : "";
  const appShellSource = readFileSync(new URL("../components/AppShell.tsx", import.meta.url), "utf8");
  const composeSource = readFileSync(new URL("../../../docker-compose.yml", import.meta.url), "utf8");

  assert.match(typesSource, /StrongStockScreeningResponse/);
  assert.match(typesSource, /GsgfAnalysis/);
  assert.match(typesSource, /GsgfFinalStatus/);
  assert.match(typesSource, /final_status: GsgfFinalStatus/);
  assert.match(typesSource, /setup_type: string \| null/);
  assert.match(typesSource, /confirm_type: string \| null/);
  assert.match(typesSource, /GsgfBacktestSummary/);
  assert.match(typesSource, /GsgfBacktestBucket/);
  assert.match(typesSource, /GsgfBacktestWindowStat/);
  assert.match(typesSource, /GsgfTradePlan/);
  assert.match(typesSource, /holder_guidance: string\[\]/);
  assert.match(typesSource, /empty_position_guidance: string\[\]/);
  assert.match(typesSource, /risk_invalidation: string\[\]/);
  assert.match(typesSource, /trade_plan: GsgfTradePlan \| null/);
  assert.match(typesSource, /GsgfReviewSummary/);
  assert.match(typesSource, /GsgfReviewSnapshotResponse/);
  assert.match(typesSource, /realized_return_pct: number \| null/);
  assert.match(typesSource, /GsgfRealCalibrationSummary/);
  assert.match(typesSource, /GsgfCalibrationBucket/);
  assert.match(typesSource, /unique_symbol_buckets: GsgfCalibrationBucket\[\]/);
  assert.match(typesSource, /GsgfChartAnnotation/);
  assert.match(typesSource, /ScreenStrategy = "strong_stock" \| "gsgf" \| "combined"/);
  assert.match(typesSource, /ScreenRunFilters/);
  assert.match(typesSource, /StrongStockIntradaySnapshot/);
  assert.match(typesSource, /GsgfIntradayConfirmation/);
  assert.match(typesSource, /gsgf_intraday_confirmation: GsgfIntradayConfirmation/);
  assert.match(typesSource, /industry: string \| null/);
  assert.match(typesSource, /industry_strength: "strong" \| "neutral" \| "weak" \| null/);
  assert.match(typesSource, /industry_score: number/);
  assert.match(typesSource, /status: "focus" \| "wait_pullback" \| "reduce_risk" \| "data_incomplete"/);
  assert.match(
    typesSource,
    /action: "watch" \| "low_buy_watch" \| "reduce" \| "avoid_chase" \| "data_incomplete"/,
  );
  assert.match(typesSource, /risk_action: "hold_watch" \| "reduce" \| "empty"/);
  assert.match(typesSource, /RiskCheckStatus = "triggered" \| "clear" \| "unknown"/);
  assert.match(typesSource, /severe_abnormal_warning: RiskCheckStatus/);
  assert.match(typesSource, /negative_news_status: RiskCheckStatus/);
  assert.match(typesSource, /negative_news_flags: string\[\]/);
  assert.doesNotMatch(typesSource, /status: .*"empty"/);
  assert.doesNotMatch(
    typesSource.slice(typesSource.indexOf("export type StrongStockIntradayItem")),
    /action: .*"empty"/,
  );
  assert.match(apiSource, /createScreenRun/);
  assert.match(apiSource, /createIntradaySnapshot/);
  assert.match(apiSource, /watchlist_text/);
  assert.match(apiSource, /use_watchlist_pool/);
  assert.match(apiSource, /gsgf_context/);
  assert.match(apiSource, /getWatchlistPool/);
  assert.match(apiSource, /saveWatchlistPool/);
  assert.match(apiSource, /addWatchlistPoolItem/);
  assert.match(apiSource, /getStockKline/);
  assert.match(apiSource, /getStockResearch/);
  assert.match(composeSource, /NEXT_PUBLIC_STRONG_STOCK_API_BASE_URL: \$\{NEXT_PUBLIC_STRONG_STOCK_API_BASE_URL:-http:\/\/localhost:8010\}/);
  assert.match(typesSource, /StockResearchResponse/);
  assert.match(typesSource, /ifind_api_key_configured: boolean/);
  assert.match(typesSource, /ifind_service_id: "hexin-ifind-ds-stock-mcp" \| "hexin-ifind-ds-news-mcp" \| "hexin-ifind-ds-index-mcp"/);
  assert.match(apiSource, /ifind_api_key\?: string \| null/);
  assert.match(apiSource, /ifind_base_url: string/);
  assert.match(apiSource, /ifind_service_id: "hexin-ifind-ds-stock-mcp" \| "hexin-ifind-ds-news-mcp" \| "hexin-ifind-ds-index-mcp"/);
  assert.match(typesSource, /note: string \| null/);
  assert.match(typesSource, /note\?: string \| null/);
  assert.match(typesSource, /ma60: number \| null/);
  assert.match(typesSource, /gsgf_annotations: GsgfChartAnnotation\[\]/);
  assert.match(apiSource, /scan_limit: scanLimit/);
  assert.match(apiSource, /filters/);
  assert.match(apiSource, /strategy\?: ScreenStrategy/);
  assert.match(apiSource, /getWatchlistGsgfStatus/);
  assert.match(apiSource, /runGsgfBacktest/);
  assert.match(apiSource, /\/api\/gsgf\/backtest/);
  assert.match(apiSource, /buildGsgfTradePlan/);
  assert.match(apiSource, /\/api\/gsgf\/trade-plan/);
  assert.match(apiSource, /saveLatestGsgfReviewSnapshot/);
  assert.match(apiSource, /recheckGsgfReview/);
  assert.match(apiSource, /\/api\/gsgf\/review\/snapshots\/latest/);
  assert.match(apiSource, /\/api\/gsgf\/review\/recheck/);
  assert.match(apiSource, /runGsgfCalibration/);
  assert.match(apiSource, /\/api\/gsgf\/calibration/);
  assert.match(componentSource, /scanLimit/);
  assert.match(componentSource, /strategy/);
  assert.match(componentSource, /股是股非模型/);
  assert.match(componentSource, /综合模型/);
  assert.match(componentSource, /股是股非结构/);
  assert.match(componentSource, /确认信号/);
  assert.match(componentSource, /setup_type/);
  assert.match(componentSource, /confirm_type/);
  assert.match(componentSource, /gsgfLabel/);
  assert.match(componentSource, /扫描候选数/);
  assert.match(componentSource, /高级筛选/);
  assert.match(componentSource, /最小市值/);
  assert.match(componentSource, /KDJ-J值/);
  assert.match(componentSource, /市场类型/);
  assert.match(componentSource, /保存筛选参数/);
  assert.match(componentSource, /筛选参数已保存到本机/);
  assert.match(componentSource, /screenFiltersSaved/);
  assert.match(pageSource, /localStorage/);
  assert.match(pageSource, /onSaveScreenFilters/);
  assert.match(pageSource, /setScreenFiltersSaved/);
  assert.match(apiSource, /getDataSourceStatus/);
  assert.match(typesSource, /MarketOverviewResponse/);
  assert.match(typesSource, /SectorRadarResponse/);
  assert.match(apiSource, /getMarketOverview/);
  assert.match(apiSource, /getSectorRadar/);
  assert.match(pageSource, /marketOverview/);
  assert.match(pageSource, /refreshMarketOverview/);
  assert.match(pageSource, /watchlistPoolItems/);
  assert.match(pageSource, /setWatchlistPoolItems\(response\.items\)/);
  assert.doesNotMatch(apiSource + componentSource + pageSource, /x-api-key|TICKFLOW_API_KEY/);
  assert.match(componentSource, /StockMaster/);
  assert.match(componentSource, /aria-label="打开自选股管理页"/);
  assert.match(componentSource, /严重异动/);
  assert.match(componentSource, /负面新闻待核验/);
  assert.match(componentSource, /近20条东方财富新闻/);
  assert.match(componentSource, /行业/);
  assert.match(componentSource, /板块强度/);
  assert.match(componentSource, /选股结果 · Screener Results/);
  assert.match(componentSource, /详情抽屉/);
  assert.match(componentSource, /数据源：/);
  assert.match(componentSource, /CandidateTable/);
  assert.match(componentSource, /CandidateDetailPanel/);
  assert.match(componentSource, /from "antd"/);
  assert.match(componentSource, /<Table/);
  assert.match(componentSource, /<Segmented/);
  assert.match(componentSource, /<Alert/);
  assert.match(componentSource, /message\.success/);
  assert.match(componentSource, /href=\{`\/stock\/\$\{item\.symbol\}`\}/);
  assert.match(componentSource, /inline-flex items-baseline gap-2 whitespace-nowrap font-black/);
  assert.match(componentSource, /selectedSymbol/);
  assert.match(componentSource, /selectedCandidateSymbols/);
  assert.match(componentSource, /candidateStatusFilter/);
  assert.match(componentSource, /gsgfSignalFilter/);
  assert.match(componentSource, /filterStockListByGsgf/);
  assert.match(componentSource, /排除全局阴量压制/);
  assert.match(componentSource, /放量突破/);
  assert.match(componentSource, /B区A点/);
  assert.match(componentSource, /GsgfTradePlanPanel/);
  assert.match(componentSource, /analysis\.trade_plan/);
  assert.match(componentSource, /持仓计划/);
  assert.match(componentSource, /空仓计划/);
  assert.match(componentSource, /失效条件/);
  assert.doesNotMatch(componentSource, /function buildLocalGsgfTradePlan/);
  assert.match(componentSource, /GsgfReviewPanel/);
  assert.match(componentSource, /信号复盘/);
  assert.match(componentSource, /保存复盘快照/);
  assert.match(componentSource, /复查信号/);
  assert.match(componentSource, /reviewSummary/);
  assert.match(componentSource, /GsgfCalibrationPanel/);
  assert.match(componentSource, /真实样本校准/);
  assert.match(componentSource, /运行校准/);
  assert.match(componentSource, /去重股票/);
  assert.match(componentSource, /hit_rate/);
  assert.match(pageSource, /calibrationSummary/);
  assert.match(pageSource, /runGsgfCalibration/);
  assert.match(pageSource, /handleRunGsgfCalibration/);
  assert.match(componentSource, /strongIndustryOnly/);
  assert.match(componentSource, /visibleCandidates/);
  assert.match(componentSource, /候选筛选/);
  assert.match(componentSource, /全部/);
  assert.match(componentSource, /强板块/);
  assert.match(componentSource, /当前筛选暂无候选/);
  assert.match(componentSource, /批量加入自选/);
  assert.match(componentSource, /已选/);
  assert.match(componentSource, /清空选择/);
  assert.doesNotMatch(componentSource, /operationTabs/);
  assert.doesNotMatch(componentSource, /activePanel/);
  assert.match(componentSource, /结构化自选池/);
  assert.match(componentSource, /watchlistPoolItems/);
  assert.doesNotMatch(componentSource, /高级文本模式/);
  assert.doesNotMatch(componentSource, /保存股票池/);
  assert.match(componentSource, /加入自选/);
  assert.match(componentSource, /watchlistMessage/);
  assert.match(componentSource, /已在自选/);
  assert.match(pageSource, /已加入自选/);
  assert.match(componentSource, /onAddToWatchlist/);
  assert.match(componentSource, /placeholder="分组"/);
  assert.match(componentSource, /placeholder="标签，逗号分隔"/);
  assert.match(componentSource, /splitTags/);
  assert.match(componentSource, /分组/);
  assert.match(componentSource, /标签/);
  assert.match(componentSource, /TickFlow/);
  assert.match(componentSource, /空仓纪律触发/);
  assert.match(componentSource, /运行筛选/);
  assert.match(componentSource, /MarketTickerBar/);
  assert.match(componentSource, /MarketEnvironmentPanel/);
  assert.match(componentSource, /FilterLogicRail/);
  assert.match(componentSource, /SectorStrengthPanel/);
  assert.match(componentSource, /TerminalMetricCard/);
  assert.match(componentSource, /TurnoverTrendPanel/);
  assert.match(componentSource, /DesignScreenerResultsTable/);
  assert.match(componentSource, /StockMaster/);
  assert.match(componentSource, /选股结果 · Screener Results/);
  assert.doesNotMatch(componentSource, /趋势 TREND/);
  assert.doesNotMatch(componentSource, /MiniTrendSparkline/);
  assert.match(componentSource, /全A成交额趋势 · A-share Turnover/);
  assert.match(componentSource, /iFinD 实时口径 · 今日相对昨日/);
  assert.match(componentSource, /TickFlow 实时口径 · 今日相对昨日/);
  assert.match(componentSource, /realtimeTurnoverSourceLabel/);
  assert.match(componentSource, /全A市场口径/);
  assert.match(componentSource, /总成交额 TOTAL TURNOVER/);
  assert.doesNotMatch(componentSource, /北向资金流入趋势 · Northbound Flow Trend/);
  assert.doesNotMatch(componentSource, /北向资金/);
  assert.match(componentSource, /情绪指数/);
  assert.match(componentSource, /涨跌比/);
  assert.match(componentSource, /上涨\/下跌/);
  assert.match(componentSource, /运行 AI 筛选/);
  assert.match(componentSource, /导出 CSV/);
  assert.doesNotMatch(componentSource, /function IntradayPanel/);
  assert.doesNotMatch(componentSource, />2\. 盘中监控</);
  assert.doesNotMatch(componentSource, /运行盘中监控/);
  assert.match(componentSource, /CandidateCardList/);
  assert.match(componentSource, /lg:hidden/);
  assert.match(componentSource, /hidden overflow-x-auto lg:block/);
  assert.match(componentSource, /max-w-none/);
  assert.match(componentSource, /grid items-stretch gap-4 xl:grid-cols-\[minmax\(0,2fr\)_minmax\(360px,1fr\)\]/);
  assert.match(componentSource, /grid gap-4 md:grid-cols-2 xl:grid-cols-4/);
  assert.doesNotMatch(componentSource, /xl:grid-cols-\[280px_minmax\(0,1fr\)_320px\]/);
  assert.doesNotMatch(componentSource, /<CandidateDetailPanel/);
  assert.match(pageSource, /ScreenerWorkbench/);
  assert.doesNotMatch(pageSource, /createIntradaySnapshot/);
  assert.doesNotMatch(pageSource + componentSource, /onRunIntraday|intradaySymbolsText|useWatchlistPool/);
  assert.match(pageSource, /addWatchlistPoolItem/);
  assert.match(pageSource, /handleAddManyToWatchlist/);
  assert.match(pageSource, /onAddManyToWatchlist/);
  assert.match(componentSource, /管理自选股/);
  assert.match(watchlistPageSource, /自选股管理/);
  assert.match(watchlistPageSource, /workbench-page/);
  assert.match(watchlistPageSource, /workbench-panel/);
  assert.match(watchlistPageSource, /from "antd"/);
  assert.match(watchlistPageSource, /<Table/);
  assert.match(watchlistPageSource, /<Form/);
  assert.match(watchlistPageSource, /<Segmented/);
  assert.match(watchlistPageSource, /<Alert/);
  assert.match(watchlistPageSource, /message\.success/);
  assert.match(watchlistPageSource, /分组/);
  assert.match(watchlistPageSource, /标签/);
  assert.match(watchlistPageSource, /备注/);
  assert.match(watchlistPageSource, /批量移动/);
  assert.match(watchlistPageSource, /删除/);
  assert.match(watchlistPageSource, /saveWatchlistPool/);
  assert.match(watchlistPageSource, /addWatchlistPoolItem/);
  assert.match(watchlistPageSource, /getWatchlistGsgfStatus/);
  assert.match(watchlistPageSource, /结构触发/);
  assert.match(watchlistPageSource, /机会触发/);
  assert.match(watchlistPageSource, /C区\/回避/);
  assert.match(settingsPageSource, /workbench-page/);
  assert.match(settingsPageSource, /workbench-panel/);
  assert.match(settingsPageSource, /loading && !config/);
  assert.match(settingsPageSource, /数据源配置/);
  assert.match(sectorsPageSource, /板块资金流/);
  assert.match(sectorsPageSource, /getSectorRadar/);
  assert.match(sectorsPageSource, /净流入/);
  assert.match(sectorsPageSource, /净流出/);
  assert.match(sectorsPageSource, /资金流口径/);
  assert.doesNotMatch(sectorsPageSource, /trailColor/);
  assert.match(sectorsPageSource, /railColor/);
  assert.match(stockPageSource, /getStockKline/);
  assert.match(stockPageSource, /getStockResearch/);
  assert.match(stockPageSource, /StockResearchResponse/);
  assert.match(stockPageSource, /TickFlowKlineChart/);
  assert.match(stockPageSource, /from "antd"/);
  assert.match(stockPageSource, /<Card/);
  assert.match(stockPageSource, /<Segmented/);
  assert.match(stockPageSource, /<Descriptions/);
  assert.match(stockPageSource, /<Alert/);
  assert.match(stockPageSource, /<Spin/);
  assert.match(stockPageSource, /GSGF 证据/);
  assert.match(stockPageSource, /showGsgfAnnotations/);
  assert.match(stockPageSource, /chartDataSource/);
  assert.match(stockPageSource, /TickFlow \/ 组件内置/);
  assert.match(stockPageSource, /组件内置源仅用于图表对照/);
  assert.match(stockChartSource, /kline-charts-react/);
  assert.match(layoutSource, /kline-charts-react\/style\.css/);
  assert.match(layoutSource, /AntdRegistry/);
  assert.match(layoutSource, /AntdAppProvider/);
  assert.match(antdProviderSource, /ConfigProvider/);
  assert.match(antdProviderSource, /zhCN/);
  assert.match(antdProviderSource, /autoInsertSpace: false/);
  assert.match(appShellSource, /antd/);
  assert.match(appShellSource, /选股工作台/);
  assert.match(appShellSource, /自选股管理/);
  assert.match(appShellSource, /板块资金流/);
  assert.match(appShellSource, /数据源配置/);
  assert.match(appShellSource, /width=\{68\}/);
  assert.match(appShellSource, /StockMaster/);
  assert.match(appShellSource, /强势股/);
  assert.match(appShellSource, /选股/);
  assert.match(appShellSource, /板块/);
  assert.match(appShellSource, /自选/);
  assert.match(appShellSource, /设置/);
  assert.match(appShellSource, /usePathname/);
  assert.doesNotMatch(appShellSource, /collapsedWidth=\{0\}/);
  assert.doesNotMatch(appShellSource, /breakpoint="lg"/);
  assert.match(stockChartSource, /dataProvider/);
  assert.match(stockChartSource, /dataSourceMode/);
  assert.match(stockChartSource, /builtinStockSdkSymbol/);
  assert.match(stockChartSource, /dataSourceMode === "tickflow"/);
  assert.match(stockChartSource, /dataProvider=\{effectiveDataProvider\}/);
  assert.match(stockChartSource, /builtinDataSourceError/);
  assert.match(stockChartSource, /handleChartError/);
  assert.match(stockChartSource, /onError=\{handleChartError\}/);
  assert.match(stockChartSource, /组件内置 K 线源加载失败/);
  assert.match(stockChartSource, /getKline/);
  assert.match(stockChartSource, /useCallback/);
  assert.match(stockChartSource, /handleDataLoad/);
  assert.match(stockChartSource, /requestOptions/);
  assert.match(stockPageSource, /StockListPanel/);
  assert.match(stockPageSource, /candidateListCollapsed/);
  assert.match(stockPageSource, /filterStockList/);
  assert.match(stockPageSource, /stockListStatusOptions/);
  assert.match(stockPageSource, /搜索候选股票/);
  assert.match(stockPageSource, /候选状态筛选/);
  assert.match(stockPageSource, /lg:grid-cols-\[168px_minmax\(0,1fr\)\]/);
  assert.match(stockPageSource, /lg:grid-cols-\[248px_minmax\(0,1fr\)\]/);
  assert.match(stockPageSource, /紧凑列表/);
  assert.match(stockPageSource, /展开股票列表|收起股票列表/);
  assert.doesNotMatch(stockPageSource, /max-w-\[30px\]/);
  assert.doesNotMatch(stockPageSource, /compactStockLabel/);
  assert.match(stockPageSource, /ChartControlBar/);
  assert.match(stockPageSource, /行情摘要/);
  assert.match(stockPageSource, /formatSourceStatus/);
  assert.match(stockPageSource, /status === "success"/);
  assert.match(stockPageSource, /可用/);
  assert.doesNotMatch(stockPageSource, /行情摘要 · \{source\} · \{status\}/);
  assert.match(stockPageSource, /股票列表/);
  assert.match(stockPageSource, /日 K 线/);
  assert.match(stockChartSource, /volume/);
  assert.match(stockChartSource, /indicatorOptions/);
  assert.match(stockChartSource, /buildKlineIndicatorOptions/);
  assert.doesNotMatch(stockChartSource, /periods: \[5, 10, 20, 60\]/);
  assert.doesNotMatch(stockPageSource, /function VolumeChart/);
  assert.doesNotMatch(stockPageSource, /function KdjChart/);
  assert.doesNotMatch(stockPageSource, /MomentumChart/);
  assert.doesNotMatch(stockPageSource, /buildMomentumPoints/);
  assert.doesNotMatch(stockPageSource, /动量/);
  assert.doesNotMatch(stockPageSource, /FAST:/);
  assert.doesNotMatch(stockPageSource, /SLOW:/);
  assert.match(stockPageSource, /KLINE_CHART_HEIGHT/);
  assert.match(stockPageSource, /h-\[calc\(100vh-236px\)\]/);
  assert.doesNotMatch(stockPageSource, /preserveAspectRatio="none"/);
  assert.doesNotMatch(stockPageSource, /data\.source_status\.detail/);
  assert.match(stockPageSource, /MovingAverageControl/);
  assert.match(stockPageSource, /type MovingAverageField = "ma5" \| "ma10" \| "ma20" \| "ma60"/);
  assert.match(stockPageSource, /visibleMovingAverages/);
  assert.match(stockPageSource, /MA60/);
  assert.match(stockPageSource, /activeChartTab/);
  assert.match(stockPageSource, /overflow-x-auto border-b border-slate-200 bg-slate-50/);
  assert.match(stockPageSource, /grid min-w-\[520px\] grid-cols-6/);
  assert.match(stockPageSource, /onChange=\{\(value\) => onChange\(value as ChartTab\)\}/);
  assert.match(stockPageSource, /研究/);
  assert.match(stockPageSource, /iFinD 研究/);
  assert.match(stockPageSource, /行业研究/);
  assert.match(stockPageSource, /财务指标/);
  assert.match(stockPageSource, /估值指标/);
  assert.match(stockPageSource, /风险事件/);
  assert.match(stockPageSource, /公司公告/);
  assert.match(stockPageSource, /新闻资讯/);
  assert.doesNotMatch(stockPageSource, /财务估值/);
  assert.doesNotMatch(stockPageSource, /公告新闻/);
  assert.doesNotMatch(stockPageSource, /title="板块强度"/);
  assert.match(stockPageSource, /setActiveChartTab/);
  assert.match(stockPageSource, /buildMovingAverageBars/);
  assert.match(stockPageSource, /buildWeeklyBars/);
  assert.match(stockChartSource, /convertBarsForKlineChart/);
  assert.doesNotMatch(stockPageSource, /chartWindowSize/);
  assert.doesNotMatch(stockPageSource, /onWheel/);
  assert.doesNotMatch(stockPageSource, /visibleBars/);
  assert.doesNotMatch(stockPageSource, /返回 \{bars\.length\} 条日K/);
  assert.doesNotMatch(stockPageSource, /xl:min-w-\[980px\]/);
  assert.doesNotMatch(stockPageSource, /xl:grid-cols-\[minmax\(0,1fr\)_270px\]/);
  assert.doesNotMatch(stockPageSource, /h-\[500px\]/);
  assert.doesNotMatch(watchlistPageSource, /盘中监控/);
  assert.doesNotMatch(componentSource + pageSource, /报告生成|历史报告|OCR|定时生成/);
  assert.match(settingsPageSource, /iFinD 研究增强/);
  assert.match(settingsPageSource, /ifind_api_key/);
  assert.match(settingsPageSource, /ifind_base_url/);
  assert.match(settingsPageSource, /hexin-ifind-ds-stock-mcp/);
  assert.match(settingsPageSource, /不替代 TickFlow 行情/);
});
