import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import test from "node:test";

test("standalone strong stock workbench is wired without daily-report modules", () => {
  const typesSource = readFileSync(new URL("./types.ts", import.meta.url), "utf8");
  const apiSource = readFileSync(new URL("./api.ts", import.meta.url), "utf8");
  const componentSource = readFileSync(new URL("../components/ScreenerWorkbench.tsx", import.meta.url), "utf8");
  const marketPanelsUrl = new URL("../components/screener/MarketOverviewPanels.tsx", import.meta.url);
  const marketPanelsSource = existsSync(marketPanelsUrl) ? readFileSync(marketPanelsUrl, "utf8") : "";
  const filterRailUrl = new URL("../components/screener/FilterLogicRail.tsx", import.meta.url);
  const filterRailSource = existsSync(filterRailUrl) ? readFileSync(filterRailUrl, "utf8") : "";
  const candidateResultsUrl = new URL("../components/screener/CandidateResults.tsx", import.meta.url);
  const candidateResultsSource = existsSync(candidateResultsUrl) ? readFileSync(candidateResultsUrl, "utf8") : "";
  const gsgfPanelsUrl = new URL("../components/screener/GsgfWorkflowPanels.tsx", import.meta.url);
  const gsgfPanelsSource = existsSync(gsgfPanelsUrl) ? readFileSync(gsgfPanelsUrl, "utf8") : "";
  const gsgfFunnelUrl = new URL("../components/screener/GsgfFunnelPanel.tsx", import.meta.url);
  const gsgfFunnelSource = existsSync(gsgfFunnelUrl) ? readFileSync(gsgfFunnelUrl, "utf8") : "";
  const screenerUtilsUrl = new URL("../components/screener/screenerUtils.ts", import.meta.url);
  const screenerUtilsSource = existsSync(screenerUtilsUrl) ? readFileSync(screenerUtilsUrl, "utf8") : "";
  const screenerTypesUrl = new URL("../components/screener/types.ts", import.meta.url);
  const screenerTypesSource = existsSync(screenerTypesUrl) ? readFileSync(screenerTypesUrl, "utf8") : "";
  const pageSource = readFileSync(new URL("../app/page.tsx", import.meta.url), "utf8");
  const homeWorkspaceUrl = new URL("../app/HomeWorkbench.tsx", import.meta.url);
  const homeWorkspaceSource = existsSync(homeWorkspaceUrl) ? readFileSync(homeWorkspaceUrl, "utf8") : "";
  const homeFeatureSource = [pageSource, homeWorkspaceSource].join("\n");
  const layoutSource = readFileSync(new URL("../app/layout.tsx", import.meta.url), "utf8");
  const antdProviderSource = readFileSync(new URL("../components/AntdAppProvider.tsx", import.meta.url), "utf8");
  const watchlistPageSource = readFileSync(new URL("../app/watchlist/page.tsx", import.meta.url), "utf8");
  const watchlistWorkspaceUrl = new URL("../app/watchlist/WatchlistWorkspace.tsx", import.meta.url);
  const watchlistWorkspaceSource = existsSync(watchlistWorkspaceUrl) ? readFileSync(watchlistWorkspaceUrl, "utf8") : "";
  const watchlistEditorUrl = new URL("../app/watchlist/WatchlistEditorPanel.tsx", import.meta.url);
  const watchlistEditorSource = existsSync(watchlistEditorUrl) ? readFileSync(watchlistEditorUrl, "utf8") : "";
  const watchlistManagerUrl = new URL("../app/watchlist/WatchlistManagerPanel.tsx", import.meta.url);
  const watchlistManagerSource = existsSync(watchlistManagerUrl) ? readFileSync(watchlistManagerUrl, "utf8") : "";
  const watchlistTypesUrl = new URL("../app/watchlist/types.ts", import.meta.url);
  const watchlistTypesSource = existsSync(watchlistTypesUrl) ? readFileSync(watchlistTypesUrl, "utf8") : "";
  const watchlistFeatureSource = [
    watchlistPageSource,
    watchlistWorkspaceSource,
    watchlistEditorSource,
    watchlistManagerSource,
    watchlistTypesSource,
  ].join("\n");
  const stockPageUrl = new URL("../app/stock/[symbol]/page.tsx", import.meta.url);
  const stockPageSource = existsSync(stockPageUrl) ? readFileSync(stockPageUrl, "utf8") : "";
  const stockWorkspaceUrl = new URL("../app/stock/[symbol]/StockKlineWorkspace.tsx", import.meta.url);
  const stockWorkspaceSource = existsSync(stockWorkspaceUrl) ? readFileSync(stockWorkspaceUrl, "utf8") : "";
  const stockFeatureSource = [stockPageSource, stockWorkspaceSource].join("\n");
  const stockChartSource = readFileSync(new URL("../components/TickFlowKlineChart.tsx", import.meta.url), "utf8");
  const settingsPageSource = readFileSync(new URL("../app/settings/page.tsx", import.meta.url), "utf8");
  const settingsWorkspaceUrl = new URL("../app/settings/SettingsWorkspace.tsx", import.meta.url);
  const settingsWorkspaceSource = existsSync(settingsWorkspaceUrl) ? readFileSync(settingsWorkspaceUrl, "utf8") : "";
  const settingsFeatureSource = [settingsPageSource, settingsWorkspaceSource].join("\n");
  const sectorsPageUrl = new URL("../app/sectors/page.tsx", import.meta.url);
  const sectorsPageSource = existsSync(sectorsPageUrl) ? readFileSync(sectorsPageUrl, "utf8") : "";
  const sectorsWorkspaceUrl = new URL("../app/sectors/SectorPageWorkspace.tsx", import.meta.url);
  const sectorsWorkspaceSource = existsSync(sectorsWorkspaceUrl) ? readFileSync(sectorsWorkspaceUrl, "utf8") : "";
  const sectorsFlowUrl = new URL("../app/sectors/SectorFlowWorkspace.tsx", import.meta.url);
  const sectorsFlowSource = existsSync(sectorsFlowUrl) ? readFileSync(sectorsFlowUrl, "utf8") : "";
  const sectorsFeatureSource = [sectorsPageSource, sectorsWorkspaceSource, sectorsFlowSource].join("\n");
  const sentimentPageUrl = new URL("../app/sentiment/page.tsx", import.meta.url);
  const sentimentPageSource = existsSync(sentimentPageUrl) ? readFileSync(sentimentPageUrl, "utf8") : "";
  const sentimentWorkspaceUrl = new URL("../app/sentiment/SentimentWorkspace.tsx", import.meta.url);
  const sentimentWorkspaceSource = existsSync(sentimentWorkspaceUrl) ? readFileSync(sentimentWorkspaceUrl, "utf8") : "";
  const sentimentIntradayUrl = new URL("../app/sentiment/IntradaySentimentPanel.tsx", import.meta.url);
  const sentimentIntradaySource = existsSync(sentimentIntradayUrl) ? readFileSync(sentimentIntradayUrl, "utf8") : "";
  const sentimentStockPoolsUrl = new URL("../app/sentiment/StockPoolTables.tsx", import.meta.url);
  const sentimentStockPoolsSource = existsSync(sentimentStockPoolsUrl) ? readFileSync(sentimentStockPoolsUrl, "utf8") : "";
  const sentimentFeatureSource = [
    sentimentPageSource,
    sentimentWorkspaceSource,
    sentimentIntradaySource,
    sentimentStockPoolsSource,
  ].join("\n");
  const screenerFeatureSource = [
    componentSource,
    marketPanelsSource,
    filterRailSource,
    candidateResultsSource,
    gsgfPanelsSource,
    gsgfFunnelSource,
    screenerUtilsSource,
    screenerTypesSource,
  ].join("\n");
  const appShellSource = readFileSync(new URL("../components/AppShell.tsx", import.meta.url), "utf8");
  const composeSource = readFileSync(new URL("../../../docker-compose.yml", import.meta.url), "utf8");

  assert.match(typesSource, /StrongStockScreeningResponse/);
  assert.match(typesSource, /GsgfAnalysis/);
  assert.match(typesSource, /GsgfFinalStatus/);
  assert.match(typesSource, /final_status: GsgfFinalStatus/);
  assert.match(typesSource, /setup_type: string \| null/);
  assert.match(typesSource, /confirm_type: string \| null/);
  assert.match(typesSource, /GsgfBacktestSummary/);
  assert.match(typesSource, /GsgfBacktestBucket/);
  assert.match(typesSource, /GsgfBacktestWindowStat/);
  assert.match(typesSource, /GsgfFunnelDiagnostics/);
  assert.match(typesSource, /gsgf_funnel: GsgfFunnelDiagnostics/);
  assert.match(typesSource, /gsgf_observation_items: StrongStockScreeningItem\[\]/);
  assert.match(typesSource, /GsgfTradePlan/);
  assert.match(typesSource, /holder_guidance: string\[\]/);
  assert.match(typesSource, /empty_position_guidance: string\[\]/);
  assert.match(typesSource, /risk_invalidation: string\[\]/);
  assert.match(typesSource, /trade_plan: GsgfTradePlan \| null/);
  assert.match(typesSource, /GsgfReviewSummary/);
  assert.match(typesSource, /GsgfReviewSnapshotResponse/);
  assert.match(typesSource, /realized_return_pct: number \| null/);
  assert.match(typesSource, /GsgfRealCalibrationSummary/);
  assert.match(typesSource, /GsgfCalibrationBucket/);
  assert.match(typesSource, /composite_score: number \| null/);
  assert.match(typesSource, /calibration_rating: string/);
  assert.match(typesSource, /unique_symbol_buckets: GsgfCalibrationBucket\[\]/);
  assert.match(typesSource, /GsgfCalibrationDiagnosticGroup/);
  assert.match(typesSource, /diagnostic_groups: GsgfCalibrationDiagnosticGroup\[\]/);
  assert.match(typesSource, /GsgfChartAnnotation/);
  assert.match(typesSource, /ScreenStrategy = "strong_stock" \| "gsgf" \| "combined"/);
  assert.match(typesSource, /ScreenRunFilters/);
  assert.match(typesSource, /StrongStockIntradaySnapshot/);
  assert.match(typesSource, /GsgfIntradayConfirmation/);
  assert.match(typesSource, /gsgf_intraday_confirmation: GsgfIntradayConfirmation/);
  assert.match(typesSource, /industry: string \| null/);
  assert.match(typesSource, /industry_strength: "strong" \| "neutral" \| "weak" \| null/);
  assert.match(typesSource, /industry_score: number/);
  assert.match(typesSource, /status: "focus" \| "wait_pullback" \| "reduce_risk" \| "data_incomplete"/);
  assert.match(
    typesSource,
    /action: "watch" \| "low_buy_watch" \| "reduce" \| "avoid_chase" \| "data_incomplete"/,
  );
  assert.match(typesSource, /risk_action: "hold_watch" \| "reduce" \| "empty"/);
  assert.match(typesSource, /RiskCheckStatus = "triggered" \| "clear" \| "unknown"/);
  assert.match(typesSource, /severe_abnormal_warning: RiskCheckStatus/);
  assert.match(typesSource, /negative_news_status: RiskCheckStatus/);
  assert.match(typesSource, /negative_news_flags: string\[\]/);
  assert.doesNotMatch(typesSource, /status: .*"empty"/);
  assert.doesNotMatch(
    typesSource.slice(typesSource.indexOf("export type StrongStockIntradayItem")),
    /action: .*"empty"/,
  );
  assert.match(apiSource, /createScreenRun/);
  assert.match(apiSource, /createIntradaySnapshot/);
  assert.match(apiSource, /watchlist_text/);
  assert.match(apiSource, /use_watchlist_pool/);
  assert.match(apiSource, /gsgf_context/);
  assert.match(apiSource, /getWatchlistPool/);
  assert.match(apiSource, /saveWatchlistPool/);
  assert.match(apiSource, /addWatchlistPoolItem/);
  assert.match(apiSource, /getStockKline/);
  assert.match(apiSource, /getStockResearch/);
  assert.match(composeSource, /NEXT_PUBLIC_STRONG_STOCK_API_BASE_URL: \$\{NEXT_PUBLIC_STRONG_STOCK_API_BASE_URL:-http:\/\/localhost:8010\}/);
  assert.match(typesSource, /StockResearchResponse/);
  assert.match(typesSource, /ifind_api_key_configured: boolean/);
  assert.match(typesSource, /ifind_service_id: "hexin-ifind-ds-stock-mcp" \| "hexin-ifind-ds-news-mcp" \| "hexin-ifind-ds-index-mcp"/);
  assert.match(apiSource, /ifind_api_key\?: string \| null/);
  assert.match(apiSource, /ifind_base_url: string/);
  assert.match(apiSource, /ifind_service_id: "hexin-ifind-ds-stock-mcp" \| "hexin-ifind-ds-news-mcp" \| "hexin-ifind-ds-index-mcp"/);
  assert.match(typesSource, /note: string \| null/);
  assert.match(typesSource, /note\?: string \| null/);
  assert.match(typesSource, /ma60: number \| null/);
  assert.match(typesSource, /gsgf_annotations: GsgfChartAnnotation\[\]/);
  assert.match(apiSource, /scan_limit: scanLimit/);
  assert.match(apiSource, /scanLimit = 160/);
  assert.match(apiSource, /filters/);
  assert.match(apiSource, /strategy\?: ScreenStrategy/);
  assert.match(apiSource, /getWatchlistGsgfStatus/);
  assert.match(apiSource, /runGsgfBacktest/);
  assert.match(apiSource, /\/api\/gsgf\/backtest/);
  assert.match(apiSource, /buildGsgfTradePlan/);
  assert.match(apiSource, /\/api\/gsgf\/trade-plan/);
  assert.match(apiSource, /saveLatestGsgfReviewSnapshot/);
  assert.match(apiSource, /recheckGsgfReview/);
  assert.match(apiSource, /\/api\/gsgf\/review\/snapshots\/latest/);
  assert.match(apiSource, /\/api\/gsgf\/review\/recheck/);
  assert.match(apiSource, /runGsgfCalibration/);
  assert.match(apiSource, /\/api\/gsgf\/calibration/);
  assert.match(screenerFeatureSource, /scanLimit/);
  assert.match(screenerFeatureSource, /strategy/);
  assert.match(screenerFeatureSource, /股是股非模型/);
  assert.match(screenerFeatureSource, /综合模型/);
  assert.match(screenerFeatureSource, /确认信号/);
  assert.match(screenerFeatureSource, /setup_type/);
  assert.match(screenerFeatureSource, /confirm_type/);
  assert.match(screenerFeatureSource, /gsgfLabel/);
  assert.match(screenerFeatureSource, /扫描候选数/);
  assert.match(screenerFeatureSource, /高级筛选/);
  assert.match(screenerFeatureSource, /最小市值/);
  assert.match(screenerFeatureSource, /KDJ-J值/);
  assert.match(screenerFeatureSource, /市场类型/);
  assert.match(screenerFeatureSource, /保存筛选参数/);
  assert.match(screenerFeatureSource, /筛选参数已保存到本机/);
  assert.match(screenerFeatureSource, /screenFiltersSaved/);
  assert.match(homeFeatureSource, /localStorage/);
  assert.match(homeFeatureSource, /onSaveScreenFilters/);
  assert.match(homeFeatureSource, /setScreenFiltersSaved/);
  assert.match(apiSource, /getDataSourceStatus/);
  assert.match(typesSource, /MarketOverviewResponse/);
  assert.match(typesSource, /MarketIndexSnapshot/);
  assert.match(typesSource, /indices: MarketIndexSnapshot\[\]/);
  assert.match(typesSource, /SectorRadarResponse/);
  assert.match(typesSource, /ShortTermSentimentResponse/);
  assert.match(typesSource, /ShortTermSentimentStockItem/);
  assert.match(typesSource, /ShortTermSentimentLadderGroup/);
  assert.match(typesSource, /ShortTermSentimentIndustryItem/);
  assert.match(typesSource, /MarketEmotionSnapshotResponse/);
  assert.match(typesSource, /MarketEmotionMetrics/);
  assert.match(typesSource, /MarketEmotionBucket/);
  assert.match(typesSource, /MarketEmotionSample/);
  assert.match(typesSource, /ShortTermIntradaySentimentResponse/);
  assert.match(typesSource, /ShortTermIntradaySentimentItem/);
  assert.match(typesSource, /ShortTermIntradaySignalDigest/);
  assert.match(typesSource, /ShortTermIntradaySignalAlert/);
  assert.match(typesSource, /NotificationChannelConfig/);
  assert.match(typesSource, /NotificationSendResult/);
  assert.match(apiSource, /getMarketOverview/);
  assert.match(apiSource, /getSectorRadar/);
  assert.match(apiSource, /getShortTermSentiment/);
  assert.match(apiSource, /getMarketEmotionSnapshot/);
  assert.match(apiSource, /getShortTermIntradaySentiment/);
  assert.match(apiSource, /getShortTermIntradaySignalDigest/);
  assert.match(apiSource, /sendNotificationMessage/);
  assert.match(apiSource, /\/api\/short-term\/sentiment/);
  assert.match(apiSource, /\/api\/short-term\/market-emotion/);
  assert.match(apiSource, /\/api\/short-term\/sentiment\/intraday/);
  assert.match(apiSource, /\/api\/short-term\/sentiment\/intraday\/digest/);
  assert.match(apiSource, /\/api\/notifications\/send/);
  assert.match(homeFeatureSource, /marketOverview/);
  assert.match(homeFeatureSource, /refreshMarketOverview/);
  assert.match(homeFeatureSource, /sectorRadar/);
  assert.match(homeFeatureSource, /refreshSectorRadar/);
  assert.match(homeFeatureSource, /getSectorRadar/);
  assert.match(homeFeatureSource, /sentimentSummary/);
  assert.match(homeFeatureSource, /refreshSentimentSummary/);
  assert.match(homeFeatureSource, /getSentimentSummary/);
  assert.match(marketPanelsSource, /sentimentSummary/);
  assert.doesNotMatch(marketPanelsSource, /const sectorSentiment = buildSectorRadarSentiment\(sectorRadar\)/);
  assert.match(homeFeatureSource, /watchlistPoolItems/);
  assert.match(homeFeatureSource, /setWatchlistPoolItems\(response\.items\)/);
  assert.doesNotMatch(apiSource + screenerFeatureSource + homeFeatureSource, /x-api-key|TICKFLOW_API_KEY/);
  assert.match(screenerFeatureSource, /StockMaster/);
  assert.match(screenerFeatureSource, /dynamic[<(]/);
  assert.match(screenerFeatureSource, /GsgfReviewPanel/);
  assert.match(screenerFeatureSource, /GsgfCalibrationPanel/);
  assert.match(marketPanelsSource, /MarketOverviewPanels/);
  assert.match(marketPanelsSource, /SectorFlowHeatmapPanel/);
  assert.match(filterRailSource, /FilterLogicRail/);
  assert.match(filterRailSource, /AdvancedScreenFilters/);
  assert.match(candidateResultsSource, /CandidateResults/);
  assert.match(candidateResultsSource, /CandidateTable/);
  assert.match(gsgfPanelsSource, /GsgfReviewPanel/);
  assert.match(gsgfPanelsSource, /GsgfCalibrationPanel/);
  assert.match(screenerUtilsSource, /export function formatCnyCompact/);
  assert.match(screenerUtilsSource, /export function exportCandidatesCsv/);
  assert.match(screenerTypesSource, /export type CandidateStatusFilter/);
  assert.match(screenerTypesSource, /export type MarketDashboardStats/);
  assert.match(screenerFeatureSource, /aria-label="打开自选股管理页"/);
  assert.match(screenerFeatureSource, /严重异动/);
  assert.match(screenerFeatureSource, /负面新闻待核验/);
  assert.match(screenerFeatureSource, /primaryRiskSummary/);
  assert.match(screenerFeatureSource, /行业/);
  assert.match(screenerFeatureSource, /板块强度/);
  assert.match(screenerFeatureSource, /选股结果 · Screener Results/);
  assert.match(screenerFeatureSource, /数据源：/);
  assert.match(screenerFeatureSource, /CandidateTable/);
  assert.match(screenerFeatureSource, /from "antd"/);
  assert.match(screenerFeatureSource, /<Table/);
  assert.match(screenerFeatureSource, /<Segmented/);
  assert.match(screenerFeatureSource, /<Alert/);
  assert.match(screenerFeatureSource, /message\.success/);
  assert.match(screenerFeatureSource, /href=\{`\/stock\/\$\{item\.symbol\}`\}/);
  assert.match(screenerFeatureSource, /block font-black text-\[#11100e\] transition hover:text-\[#f04438\]/);
  assert.match(screenerFeatureSource, /selectedSymbol/);
  assert.match(screenerFeatureSource, /selectedCandidateSymbols/);
  assert.match(screenerFeatureSource, /candidateStatusFilter/);
  assert.match(screenerFeatureSource, /gsgfSignalFilter/);
  assert.match(screenerFeatureSource, /filterStockListByGsgf/);
  assert.match(screenerFeatureSource, /排除全局阴量压制/);
  assert.match(screenerFeatureSource, /放量突破/);
  assert.match(screenerFeatureSource, /B区A点/);
  assert.doesNotMatch(screenerFeatureSource, /CandidateDetailPanel/);
  assert.doesNotMatch(screenerFeatureSource, /详情抽屉/);
  assert.doesNotMatch(screenerFeatureSource, /GsgfTradePlanPanel/);
  assert.doesNotMatch(screenerFeatureSource, /analysis\.trade_plan/);
  assert.doesNotMatch(screenerFeatureSource, /function buildLocalGsgfTradePlan/);
  assert.match(screenerFeatureSource, /GsgfReviewPanel/);
  assert.match(screenerFeatureSource, /信号复盘/);
  assert.match(screenerFeatureSource, /保存复盘快照/);
  assert.match(screenerFeatureSource, /复查信号/);
  assert.match(screenerFeatureSource, /reviewSummary/);
  assert.match(screenerFeatureSource, /GsgfCalibrationPanel/);
  assert.match(screenerFeatureSource, /真实样本校准/);
  assert.match(screenerFeatureSource, /运行校准/);
  assert.match(screenerFeatureSource, /综合分/);
  assert.match(screenerFeatureSource, /评级/);
  assert.match(screenerFeatureSource, /诊断分桶/);
  assert.match(screenerFeatureSource, /确认信号/);
  assert.match(screenerFeatureSource, /准备形态/);
  assert.match(screenerFeatureSource, /结构区间/);
  assert.match(screenerFeatureSource, /评分段/);
  assert.match(screenerFeatureSource, /信号后T\+演化/);
  assert.match(screenerFeatureSource, /最大回撤/);
  assert.match(screenerFeatureSource, /GsgfFunnelPanel/);
  assert.match(screenerFeatureSource, /漏斗诊断/);
  assert.match(screenerFeatureSource, /扫描覆盖/);
  assert.match(screenerFeatureSource, /早期观察池/);
  assert.match(screenerFeatureSource, /gsgf_observation_items/);
  assert.match(screenerFeatureSource, /去重股票/);
  assert.match(screenerFeatureSource, /hit_rate/);
  assert.match(homeFeatureSource, /calibrationSummary/);
  assert.match(homeFeatureSource, /runGsgfCalibration/);
  assert.match(homeFeatureSource, /handleRunGsgfCalibration/);
  assert.match(screenerFeatureSource, /strongIndustryOnly/);
  assert.match(screenerFeatureSource, /visibleCandidates/);
  assert.match(screenerFeatureSource, /候选筛选/);
  assert.match(screenerFeatureSource, /全部/);
  assert.match(screenerFeatureSource, /强板块/);
  assert.match(screenerFeatureSource, /当前筛选暂无候选/);
  assert.match(screenerFeatureSource, /批量加入自选/);
  assert.match(screenerFeatureSource, /已选/);
  assert.match(screenerFeatureSource, /清空选择/);
  assert.doesNotMatch(screenerFeatureSource, /operationTabs/);
  assert.doesNotMatch(screenerFeatureSource, /activePanel/);
  assert.match(screenerFeatureSource, /结构化自选池/);
  assert.match(screenerFeatureSource, /watchlistPoolItems/);
  assert.doesNotMatch(screenerFeatureSource, /高级文本模式/);
  assert.doesNotMatch(screenerFeatureSource, /保存股票池/);
  assert.match(screenerFeatureSource, /加入自选/);
  assert.match(screenerFeatureSource, /watchlistMessage/);
  assert.match(screenerFeatureSource, /已在自选/);
  assert.match(homeFeatureSource, /已加入自选/);
  assert.match(screenerFeatureSource, /onAddToWatchlist/);
  assert.match(screenerFeatureSource, /placeholder="批量分组"/);
  assert.match(screenerFeatureSource, /placeholder="批量标签，逗号分隔"/);
  assert.match(screenerFeatureSource, /splitTags/);
  assert.match(screenerFeatureSource, /分组/);
  assert.match(screenerFeatureSource, /标签/);
  assert.match(screenerFeatureSource, /TickFlow/);
  assert.match(screenerFeatureSource, /运行筛选/);
  assert.match(screenerFeatureSource, /MarketTickerBar/);
  assert.match(screenerFeatureSource, /findMarketIndex\(indices, "399006\.SZ", "创业板"\)/);
  assert.match(screenerFeatureSource, /findMarketIndex\(indices, "000688\.SH", "科创50"\)/);
  assert.match(screenerFeatureSource, /formatSignedPercent\(changePct\)/);
  assert.match(screenerFeatureSource, /MarketEnvironmentPanel/);
  assert.match(screenerFeatureSource, /FilterLogicRail/);
  assert.match(screenerFeatureSource, /SectorStrengthPanel/);
  assert.match(screenerFeatureSource, /sectorRadar/);
  assert.match(screenerFeatureSource, /SectorRadarResponse/);
  assert.match(screenerFeatureSource, /SectorRadarItem/);
  assert.match(screenerFeatureSource, /SectorFlowHeatmapPanel/);
  assert.match(screenerFeatureSource, /板块资金流热力/);
  assert.match(screenerFeatureSource, /净流入 Top5/);
  assert.match(screenerFeatureSource, /净流出 Top5/);
  assert.match(screenerFeatureSource, /板块强度待接入/);
  assert.match(screenerFeatureSource, /后续将接入非资金流口径的板块强度模型/);
  assert.doesNotMatch(screenerFeatureSource, /<SectorRadarGroup/);
  assert.doesNotMatch(screenerFeatureSource, /<SectorStrengthRow/);
  assert.doesNotMatch(screenerFeatureSource, /buildSectorStrengthItems/);
  assert.match(screenerFeatureSource, /TerminalMetricCard/);
  assert.doesNotMatch(screenerFeatureSource, /TurnoverTrendPanel/);
  assert.match(screenerFeatureSource, /DesignScreenerResultsTable/);
  assert.match(screenerFeatureSource, /StockMaster/);
  assert.match(screenerFeatureSource, /选股结果 · Screener Results/);
  assert.doesNotMatch(screenerFeatureSource, /趋势 TREND/);
  assert.doesNotMatch(screenerFeatureSource, /MiniTrendSparkline/);
  assert.doesNotMatch(screenerFeatureSource, /全A成交额趋势 · A-share Turnover/);
  assert.match(screenerFeatureSource, /iFinD 实时口径 · 今日相对昨日/);
  assert.match(screenerFeatureSource, /TickFlow 实时口径 · 今日相对昨日/);
  assert.match(screenerFeatureSource, /realtimeTurnoverSourceLabel/);
  assert.match(screenerFeatureSource, /全A市场口径/);
  assert.match(screenerFeatureSource, /总成交额 TOTAL TURNOVER/);
  assert.doesNotMatch(screenerFeatureSource, /北向资金流入趋势 · Northbound Flow Trend/);
  assert.doesNotMatch(screenerFeatureSource, /北向资金/);
  assert.match(screenerFeatureSource, /情绪指数/);
  assert.match(screenerFeatureSource, /涨跌比/);
  assert.match(screenerFeatureSource, /上涨\/下跌/);
  assert.match(screenerFeatureSource, /运行 AI 筛选/);
  assert.match(screenerFeatureSource, /导出 CSV/);
  assert.doesNotMatch(screenerFeatureSource, /function IntradayPanel/);
  assert.doesNotMatch(screenerFeatureSource, />2\. 盘中监控</);
  assert.doesNotMatch(screenerFeatureSource, /运行盘中监控/);
  assert.match(screenerFeatureSource, /CandidateCardList/);
  assert.match(screenerFeatureSource, /lg:hidden/);
  assert.match(screenerFeatureSource, /hidden overflow-x-auto lg:block/);
  assert.match(screenerFeatureSource, /max-w-none/);
  assert.match(screenerFeatureSource, /grid items-stretch gap-4 xl:grid-cols-\[minmax\(0,2fr\)_minmax\(360px,1fr\)\]/);
  assert.match(screenerFeatureSource, /grid gap-4 md:grid-cols-2 xl:grid-cols-4/);
  assert.doesNotMatch(screenerFeatureSource, /xl:grid-cols-\[280px_minmax\(0,1fr\)_320px\]/);
  assert.match(screenerFeatureSource, /点击股票名称查看 K 线详情/);
  assert.match(pageSource, /dynamic[<(]/);
  assert.match(pageSource, /HomeWorkbench/);
  assert.match(homeFeatureSource, /ScreenerWorkbench/);
  assert.match(homeFeatureSource, /const \[scanLimit, setScanLimit\] = useState\(160\)/);
  assert.doesNotMatch(homeFeatureSource, /createIntradaySnapshot/);
  assert.doesNotMatch(homeFeatureSource + screenerFeatureSource, /onRunIntraday|intradaySymbolsText|useWatchlistPool/);
  assert.match(homeFeatureSource, /addWatchlistPoolItem/);
  assert.match(homeFeatureSource, /handleAddManyToWatchlist/);
  assert.match(homeFeatureSource, /onAddManyToWatchlist/);
  assert.match(screenerFeatureSource, /管理自选股/);
  assert.match(watchlistFeatureSource, /自选股管理/);
  assert.match(watchlistPageSource, /WatchlistWorkspace/);
  assert.match(watchlistFeatureSource, /dynamic[<(]/);
  assert.match(watchlistFeatureSource, /WatchlistEditorPanel/);
  assert.match(watchlistFeatureSource, /WatchlistManagerPanel/);
  assert.match(watchlistFeatureSource, /workbench-page/);
  assert.match(watchlistFeatureSource, /workbench-panel/);
  assert.match(watchlistFeatureSource, /from "antd"/);
  assert.match(watchlistFeatureSource, /<Table/);
  assert.match(watchlistFeatureSource, /<Form/);
  assert.match(watchlistFeatureSource, /<Segmented/);
  assert.match(watchlistFeatureSource, /<Alert/);
  assert.match(watchlistFeatureSource, /message\.success/);
  assert.match(watchlistFeatureSource, /分组/);
  assert.match(watchlistFeatureSource, /标签/);
  assert.match(watchlistFeatureSource, /备注/);
  assert.match(watchlistFeatureSource, /批量移动/);
  assert.match(watchlistFeatureSource, /删除/);
  assert.match(watchlistFeatureSource, /saveWatchlistPool/);
  assert.match(watchlistFeatureSource, /addWatchlistPoolItem/);
  assert.match(watchlistFeatureSource, /getWatchlistGsgfStatus/);
  assert.match(watchlistFeatureSource, /结构触发/);
  assert.match(watchlistFeatureSource, /机会触发/);
  assert.match(watchlistFeatureSource, /C区\/回避/);
  assert.match(settingsPageSource, /workbench-page/);
  assert.match(settingsPageSource, /workbench-panel/);
  assert.match(settingsFeatureSource, /loading && !config/);
  assert.match(settingsPageSource, /数据源配置/);
  assert.match(settingsPageSource, /dynamic[<(]/);
  assert.match(settingsPageSource, /SettingsWorkspace/);
  assert.match(sectorsFeatureSource, /板块资金流/);
  assert.match(sectorsFeatureSource, /getSectorRadar/);
  assert.match(sectorsFeatureSource, /净流入/);
  assert.match(sectorsFeatureSource, /净流出/);
  assert.match(sectorsFeatureSource, /资金流口径/);
  assert.doesNotMatch(sectorsFeatureSource, /trailColor/);
  assert.match(sectorsFeatureSource, /railColor/);
  assert.match(sectorsPageSource, /dynamic[<(]/);
  assert.match(sectorsPageSource, /SectorPageWorkspace/);
  assert.match(sentimentPageSource, /SentimentWorkspace/);
  assert.match(sentimentFeatureSource, /短线情绪中心/);
  assert.match(sentimentFeatureSource, /市场情绪仪表盘/);
  assert.match(sentimentFeatureSource, /情绪指标/);
  assert.match(sentimentFeatureSource, /亏钱效应/);
  assert.match(sentimentFeatureSource, /今日封板率/);
  assert.match(sentimentFeatureSource, /涨跌幅分布/);
  assert.match(sentimentFeatureSource, /日内情绪落点/);
  assert.match(sentimentFeatureSource, /EmotionHistoryChart/);
  assert.match(sentimentFeatureSource, /真实采样曲线/);
  assert.match(sentimentFeatureSource, /getSentimentSummary/);
  assert.match(sentimentFeatureSource, /getSentimentDetail/);
  assert.match(sentimentFeatureSource, /涨停池/);
  assert.match(sentimentFeatureSource, /炸板池/);
  assert.match(sentimentFeatureSource, /连板天梯/);
  assert.match(sentimentFeatureSource, /盘中情绪快照/);
  assert.match(sentimentFeatureSource, /TickFlow 实时行情/);
  assert.match(sentimentFeatureSource, /getShortTermIntradaySentiment/);
  assert.match(sentimentFeatureSource, /getShortTermIntradaySignalDigest/);
  assert.match(sentimentFeatureSource, /提醒草稿/);
  assert.match(sentimentFeatureSource, /复制草稿/);
  assert.match(sentimentFeatureSource, /发送草稿/);
  assert.match(sentimentFeatureSource, /sendNotificationMessage/);
  assert.match(sentimentFeatureSource, /后台监控/);
  assert.match(sentimentFeatureSource, /getSentimentMonitorStatus/);
  assert.match(sentimentFeatureSource, /startSentimentMonitor/);
  assert.match(sentimentFeatureSource, /stopSentimentMonitor/);
  assert.match(sentimentFeatureSource, /runSentimentMonitorOnce/);
  assert.doesNotMatch(sentimentFeatureSource, /<Alert[^>]*message=/);
  assert.doesNotMatch(sectorsFeatureSource, /<Alert[^>]*message=/);
  assert.match(sentimentFeatureSource, /ShortTermSentimentResponse/);
  assert.match(sentimentFeatureSource, /ShortTermIntradaySentimentResponse/);
  assert.match(sentimentFeatureSource, /ShortTermIntradaySignalDigest/);
  assert.match(sentimentPageSource, /dynamic[<(]/);
  assert.match(sentimentFeatureSource, /IntradaySentimentPanel/);
  assert.match(sentimentFeatureSource, /StockPoolTable/);
  assert.match(stockPageSource, /dynamic[<(]/);
  assert.match(stockPageSource, /StockKlineWorkspace/);
  assert.match(stockFeatureSource, /getStockKline/);
  assert.match(stockFeatureSource, /getStockResearch/);
  assert.match(stockFeatureSource, /shouldLoadResearch/);
  assert.match(stockFeatureSource, /StockResearchResponse/);
  assert.match(stockFeatureSource, /TickFlowKlineChart/);
  assert.match(stockPageSource, /kline-charts-react\/style\.css/);
  assert.match(stockFeatureSource, /from "antd"/);
  assert.match(stockFeatureSource, /<Card/);
  assert.match(stockFeatureSource, /<Segmented/);
  assert.match(stockFeatureSource, /<Alert/);
  assert.match(stockFeatureSource, /<Spin/);
  assert.match(stockFeatureSource, /GSGF 证据/);
  assert.match(stockFeatureSource, /showGsgfAnnotations/);
  assert.match(stockFeatureSource, /annotationCount/);
  assert.match(stockFeatureSource, /canShowGsgfAnnotations/);
  assert.match(stockFeatureSource, /GsgfEvidenceSummary/);
  assert.match(stockFeatureSource, /显示证据/);
  assert.match(stockFeatureSource, /隐藏证据/);
  assert.match(stockFeatureSource, /chartDataSource/);
  assert.match(stockFeatureSource, /TickFlow \/ 组件内置/);
  assert.match(stockFeatureSource, /组件内置源仅用于图表对照/);
  assert.match(stockChartSource, /kline-charts-react/);
  assert.doesNotMatch(layoutSource, /kline-charts-react\/style\.css/);
  assert.match(sentimentFeatureSource, /loadSentimentDetail/);
  assert.match(sentimentFeatureSource, /void loadSentimentDetail/);
  assert.match(layoutSource, /AntdRegistry/);
  assert.match(layoutSource, /AntdAppProvider/);
  assert.match(antdProviderSource, /ConfigProvider/);
  assert.match(antdProviderSource, /zhCN/);
  assert.match(antdProviderSource, /autoInsertSpace: false/);
  assert.match(appShellSource, /antd/);
  assert.match(appShellSource, /选股工作台/);
  assert.match(appShellSource, /自选股管理/);
  assert.match(appShellSource, /板块资金流/);
  assert.match(appShellSource, /短线情绪/);
  assert.match(appShellSource, /\/sentiment/);
  assert.match(appShellSource, /数据源配置/);
  assert.match(appShellSource, /width=\{68\}/);
  assert.match(appShellSource, /StockMaster/);
  assert.match(appShellSource, /强势股/);
  assert.match(appShellSource, /选股/);
  assert.match(appShellSource, /板块/);
  assert.match(appShellSource, /自选/);
  assert.match(appShellSource, /设置/);
  assert.match(appShellSource, /usePathname/);
  assert.doesNotMatch(appShellSource, /collapsedWidth=\{0\}/);
  assert.doesNotMatch(appShellSource, /breakpoint="lg"/);
  assert.match(stockChartSource, /dataProvider/);
  assert.match(stockChartSource, /dataSourceMode/);
  assert.match(stockChartSource, /builtinStockSdkSymbol/);
  assert.match(stockChartSource, /dataSourceMode === "tickflow"/);
  assert.match(stockChartSource, /dataProvider=\{effectiveDataProvider\}/);
  assert.match(stockChartSource, /builtinDataSourceError/);
  assert.match(stockChartSource, /handleChartError/);
  assert.match(stockChartSource, /onError=\{handleChartError\}/);
  assert.match(stockChartSource, /组件内置 K 线源加载失败/);
  assert.match(stockChartSource, /getKline/);
  assert.match(stockChartSource, /useCallback/);
  assert.match(stockChartSource, /handleDataLoad/);
  assert.match(stockChartSource, /requestOptions/);
  assert.match(stockFeatureSource, /StockListPanel/);
  assert.match(stockFeatureSource, /candidateListCollapsed/);
  assert.match(stockFeatureSource, /const \[candidateListCollapsed, setCandidateListCollapsed\] = useState\(false\)/);
  assert.match(stockFeatureSource, /filterStockList/);
  assert.match(stockFeatureSource, /stockListStatusOptions/);
  assert.match(stockFeatureSource, /搜索候选股票/);
  assert.match(stockFeatureSource, /候选状态筛选/);
  assert.match(stockFeatureSource, /lg:grid-cols-\[168px_minmax\(0,1fr\)\]/);
  assert.match(stockFeatureSource, /lg:grid-cols-\[248px_minmax\(0,1fr\)\]/);
  assert.match(stockFeatureSource, /紧凑列表/);
  assert.match(stockFeatureSource, /展开股票列表|收起股票列表/);
  assert.doesNotMatch(stockFeatureSource, /max-w-\[30px\]/);
  assert.doesNotMatch(stockFeatureSource, /compactStockLabel/);
  assert.match(stockFeatureSource, /ChartControlBar/);
  assert.match(stockFeatureSource, /行情摘要/);
  assert.match(apiSource, /getStockQuote/);
  assert.match(typesSource, /StockQuoteResponse/);
  assert.match(stockFeatureSource, /formatTurnoverRate\(quote\?\.turnoverRate \?\? null\)/);
  assert.doesNotMatch(stockFeatureSource, /<HeaderMetric label="换" value="--" \/>/);
  assert.match(stockFeatureSource, /formatSourceStatus/);
  assert.match(stockFeatureSource, /status === "success"/);
  assert.match(stockFeatureSource, /可用/);
  assert.doesNotMatch(stockFeatureSource, /行情摘要 · \{source\} · \{status\}/);
  assert.match(stockFeatureSource, /股票列表/);
  assert.match(stockFeatureSource, /日 K 线/);
  assert.match(stockChartSource, /volume/);
  assert.match(stockChartSource, /indicatorOptions/);
  assert.match(stockChartSource, /buildKlineIndicatorOptions/);
  assert.doesNotMatch(stockChartSource, /periods: \[5, 10, 20, 60\]/);
  assert.doesNotMatch(stockFeatureSource, /function VolumeChart/);
  assert.doesNotMatch(stockFeatureSource, /function KdjChart/);
  assert.doesNotMatch(stockFeatureSource, /MomentumChart/);
  assert.doesNotMatch(stockFeatureSource, /buildMomentumPoints/);
  assert.doesNotMatch(stockFeatureSource, /动量/);
  assert.doesNotMatch(stockFeatureSource, /FAST:/);
  assert.doesNotMatch(stockFeatureSource, /SLOW:/);
  assert.match(stockFeatureSource, /KLINE_CHART_HEIGHT/);
  assert.match(stockFeatureSource, /h-\[calc\(100vh-236px\)\]/);
  assert.doesNotMatch(stockFeatureSource, /preserveAspectRatio="none"/);
  assert.doesNotMatch(stockFeatureSource, /data\.source_status\.detail/);
  assert.match(stockFeatureSource, /MovingAverageControl/);
  assert.match(stockFeatureSource, /type MovingAverageField = "ma5" \| "ma10" \| "ma20" \| "ma60"/);
  assert.match(stockFeatureSource, /visibleMovingAverages/);
  assert.match(stockFeatureSource, /MA60/);
  assert.match(stockFeatureSource, /activeChartTab/);
  assert.match(stockFeatureSource, /overflow-x-auto border-b border-slate-200 bg-slate-50/);
  assert.match(stockFeatureSource, /grid min-w-\[520px\] grid-cols-5/);
  assert.match(stockFeatureSource, /onChange=\{\(value\) => onChange\(value as ChartTab\)\}/);
  assert.doesNotMatch(stockFeatureSource, /key: "research"/);
  assert.doesNotMatch(stockFeatureSource, /label: "研究"/);
  assert.doesNotMatch(stockFeatureSource, /activeTab === "research"/);
  assert.doesNotMatch(stockFeatureSource, /iFinD 研究/);
  assert.doesNotMatch(stockFeatureSource, /<ResearchPanel/);
  assert.doesNotMatch(stockFeatureSource, /label="K线数量"/);
  assert.doesNotMatch(stockFeatureSource, /label="MA5"/);
  assert.doesNotMatch(stockFeatureSource, /label="MA10"/);
  assert.doesNotMatch(stockFeatureSource, /label="MA20"/);
  assert.doesNotMatch(stockFeatureSource, /label="MA60"/);
  assert.match(stockFeatureSource, /总市值/);
  assert.match(stockFeatureSource, /动态市盈率/);
  assert.match(stockFeatureSource, /静态市盈率/);
  assert.match(stockFeatureSource, /股是股非模型选股条件/);
  assert.doesNotMatch(stockFeatureSource, /财务估值/);
  assert.doesNotMatch(stockFeatureSource, /公告新闻/);
  assert.doesNotMatch(stockFeatureSource, /title="板块强度"/);
  assert.match(stockFeatureSource, /setActiveChartTab/);
  assert.match(stockFeatureSource, /buildMovingAverageBars/);
  assert.match(stockFeatureSource, /buildWeeklyBars/);
  assert.match(stockChartSource, /convertBarsForKlineChart/);
  assert.doesNotMatch(stockFeatureSource, /chartWindowSize/);
  assert.doesNotMatch(stockFeatureSource, /onWheel/);
  assert.doesNotMatch(stockFeatureSource, /visibleBars/);
  assert.doesNotMatch(stockFeatureSource, /返回 \{bars\.length\} 条日K/);
  assert.doesNotMatch(stockFeatureSource, /xl:min-w-\[980px\]/);
  assert.doesNotMatch(stockFeatureSource, /xl:grid-cols-\[minmax\(0,1fr\)_270px\]/);
  assert.doesNotMatch(stockFeatureSource, /h-\[500px\]/);
  assert.doesNotMatch(watchlistFeatureSource, /盘中监控/);
  assert.doesNotMatch(screenerFeatureSource + homeFeatureSource, /报告生成|历史报告|OCR|定时生成/);
  assert.match(settingsFeatureSource, /iFinD 研究增强/);
  assert.match(settingsFeatureSource, /通知渠道/);
  assert.match(settingsFeatureSource, /企业微信/);
  assert.match(settingsFeatureSource, /飞书/);
  assert.match(settingsFeatureSource, /Telegram/);
  assert.match(settingsFeatureSource, /邮件/);
  assert.match(settingsFeatureSource, /ifind_api_key/);
  assert.match(settingsFeatureSource, /ifind_base_url/);
  assert.match(settingsFeatureSource, /hexin-ifind-ds-stock-mcp/);
  assert.match(settingsFeatureSource, /不替代 TickFlow 行情/);
});
