import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import test from "node:test";

test("standalone strong stock workbench is wired without daily-report modules", () => {
  const typesSource = readFileSync(new URL("./types.ts", import.meta.url), "utf8");
  const apiSource = readFileSync(new URL("./api.ts", import.meta.url), "utf8");
  const componentSource = readFileSync(new URL("../components/ScreenerWorkbench.tsx", import.meta.url), "utf8");
  const pageSource = readFileSync(new URL("../app/page.tsx", import.meta.url), "utf8");
  const watchlistPageSource = readFileSync(new URL("../app/watchlist/page.tsx", import.meta.url), "utf8");
  const stockPageUrl = new URL("../app/stock/[symbol]/page.tsx", import.meta.url);
  const stockPageSource = existsSync(stockPageUrl) ? readFileSync(stockPageUrl, "utf8") : "";
  const settingsPageSource = readFileSync(new URL("../app/settings/page.tsx", import.meta.url), "utf8");
  const composeSource = readFileSync(new URL("../../../docker-compose.yml", import.meta.url), "utf8");

  assert.match(typesSource, /StrongStockScreeningResponse/);
  assert.match(typesSource, /GsgfAnalysis/);
  assert.match(typesSource, /ScreenStrategy = "strong_stock" \| "gsgf" \| "combined"/);
  assert.match(typesSource, /ScreenRunFilters/);
  assert.match(typesSource, /StrongStockIntradaySnapshot/);
  assert.match(typesSource, /industry: string \| null/);
  assert.match(typesSource, /industry_strength: "strong" \| "neutral" \| "weak" \| null/);
  assert.match(typesSource, /industry_score: number/);
  assert.match(typesSource, /status: "focus" \| "wait_pullback" \| "reduce_risk" \| "data_incomplete"/);
  assert.match(
    typesSource,
    /action: "watch" \| "low_buy_watch" \| "reduce" \| "avoid_chase" \| "data_incomplete"/,
  );
  assert.match(typesSource, /risk_action: "hold_watch" \| "reduce" \| "empty"/);
  assert.match(typesSource, /RiskCheckStatus = "triggered" \| "clear" \| "unknown"/);
  assert.match(typesSource, /severe_abnormal_warning: RiskCheckStatus/);
  assert.match(typesSource, /negative_news_status: RiskCheckStatus/);
  assert.match(typesSource, /negative_news_flags: string\[\]/);
  assert.doesNotMatch(typesSource, /status: .*"empty"/);
  assert.doesNotMatch(
    typesSource.slice(typesSource.indexOf("export type StrongStockIntradayItem")),
    /action: .*"empty"/,
  );
  assert.match(apiSource, /createScreenRun/);
  assert.match(apiSource, /createIntradaySnapshot/);
  assert.match(apiSource, /watchlist_text/);
  assert.match(apiSource, /use_watchlist_pool/);
  assert.match(apiSource, /getWatchlistPool/);
  assert.match(apiSource, /saveWatchlistPool/);
  assert.match(apiSource, /addWatchlistPoolItem/);
  assert.match(apiSource, /getStockKline/);
  assert.match(apiSource, /getStockResearch/);
  assert.match(composeSource, /NEXT_PUBLIC_STRONG_STOCK_API_BASE_URL: \$\{NEXT_PUBLIC_STRONG_STOCK_API_BASE_URL:-http:\/\/localhost:8010\}/);
  assert.match(typesSource, /StockResearchResponse/);
  assert.match(typesSource, /ifind_api_key_configured: boolean/);
  assert.match(typesSource, /ifind_service_id: "hexin-ifind-ds-stock-mcp" \| "hexin-ifind-ds-news-mcp" \| "hexin-ifind-ds-index-mcp"/);
  assert.match(apiSource, /ifind_api_key\?: string \| null/);
  assert.match(apiSource, /ifind_base_url: string/);
  assert.match(apiSource, /ifind_service_id: "hexin-ifind-ds-stock-mcp" \| "hexin-ifind-ds-news-mcp" \| "hexin-ifind-ds-index-mcp"/);
  assert.match(typesSource, /note: string \| null/);
  assert.match(typesSource, /note\?: string \| null/);
  assert.match(typesSource, /ma60: number \| null/);
  assert.match(apiSource, /scan_limit: scanLimit/);
  assert.match(apiSource, /filters/);
  assert.match(apiSource, /strategy\?: ScreenStrategy/);
  assert.match(apiSource, /getWatchlistGsgfStatus/);
  assert.match(componentSource, /scanLimit/);
  assert.match(componentSource, /扫描候选数/);
  assert.match(componentSource, /高级筛选/);
  assert.match(componentSource, /最小市值/);
  assert.match(componentSource, /KDJ-J值/);
  assert.match(componentSource, /市场类型/);
  assert.match(componentSource, /保存筛选参数/);
  assert.match(componentSource, /筛选参数已保存到本机/);
  assert.match(componentSource, /screenFiltersSaved/);
  assert.match(pageSource, /localStorage/);
  assert.match(pageSource, /onSaveScreenFilters/);
  assert.match(pageSource, /setScreenFiltersSaved/);
  assert.match(apiSource, /getDataSourceStatus/);
  assert.match(pageSource, /watchlistPoolItems/);
  assert.match(pageSource, /setWatchlistPoolItems\(response\.items\)/);
  assert.doesNotMatch(apiSource + componentSource + pageSource, /x-api-key|TICKFLOW_API_KEY/);
  assert.match(componentSource, /强势股选股工作台/);
  assert.match(componentSource, /aria-label="打开自选股管理页"/);
  assert.match(componentSource, /严重异动/);
  assert.match(componentSource, /负面新闻待核验/);
  assert.match(componentSource, /近20条东方财富新闻/);
  assert.match(componentSource, /行业/);
  assert.match(componentSource, /板块强度/);
  assert.match(componentSource, /今日流程/);
  assert.match(componentSource, /候选决策表/);
  assert.match(componentSource, /详情抽屉/);
  assert.match(componentSource, /数据源：/);
  assert.match(componentSource, /CandidateTable/);
  assert.match(componentSource, /CandidateDetailPanel/);
  assert.match(componentSource, /href=\{`\/stock\/\$\{item\.symbol\}`\}/);
  assert.match(componentSource, /inline-flex items-baseline gap-2 whitespace-nowrap font-black/);
  assert.match(componentSource, /selectedSymbol/);
  assert.match(componentSource, /selectedCandidateSymbols/);
  assert.match(componentSource, /candidateStatusFilter/);
  assert.match(componentSource, /strongIndustryOnly/);
  assert.match(componentSource, /visibleCandidates/);
  assert.match(componentSource, /候选筛选/);
  assert.match(componentSource, /全部/);
  assert.match(componentSource, /强板块/);
  assert.match(componentSource, /当前筛选暂无候选/);
  assert.match(componentSource, /批量加入自选/);
  assert.match(componentSource, /已选/);
  assert.match(componentSource, /清空选择/);
  assert.doesNotMatch(componentSource, /operationTabs/);
  assert.doesNotMatch(componentSource, /activePanel/);
  assert.match(componentSource, /结构化自选池/);
  assert.match(componentSource, /watchlistPoolItems/);
  assert.doesNotMatch(componentSource, /高级文本模式/);
  assert.doesNotMatch(componentSource, /保存股票池/);
  assert.match(componentSource, /加入自选/);
  assert.match(componentSource, /watchlistMessage/);
  assert.match(componentSource, /已在自选/);
  assert.match(pageSource, /已加入自选/);
  assert.match(componentSource, /onAddToWatchlist/);
  assert.match(componentSource, /placeholder="分组"/);
  assert.match(componentSource, /placeholder="标签，逗号分隔"/);
  assert.match(componentSource, /splitTags/);
  assert.match(componentSource, /分组/);
  assert.match(componentSource, /标签/);
  assert.match(componentSource, /TickFlow/);
  assert.match(componentSource, /空仓纪律触发/);
  assert.match(componentSource, /运行筛选/);
  assert.doesNotMatch(componentSource, /function IntradayPanel/);
  assert.doesNotMatch(componentSource, />2\. 盘中监控</);
  assert.doesNotMatch(componentSource, /运行盘中监控/);
  assert.match(componentSource, /CandidateCardList/);
  assert.match(componentSource, /lg:hidden/);
  assert.match(componentSource, /hidden overflow-x-auto lg:block/);
  assert.match(componentSource, /xl:grid-cols-\[280px_minmax\(0,1fr\)_320px\]/);
  assert.match(componentSource, /xl:sticky xl:top-4 xl:max-h-\[calc\(100vh-2rem\)\] xl:overflow-y-auto/);
  assert.match(pageSource, /ScreenerWorkbench/);
  assert.doesNotMatch(pageSource, /createIntradaySnapshot/);
  assert.doesNotMatch(pageSource + componentSource, /onRunIntraday|intradaySymbolsText|useWatchlistPool/);
  assert.match(pageSource, /addWatchlistPoolItem/);
  assert.match(pageSource, /handleAddManyToWatchlist/);
  assert.match(pageSource, /onAddManyToWatchlist/);
  assert.match(componentSource, /管理自选股/);
  assert.match(watchlistPageSource, /自选股管理/);
  assert.match(watchlistPageSource, /分组/);
  assert.match(watchlistPageSource, /标签/);
  assert.match(watchlistPageSource, /备注/);
  assert.match(watchlistPageSource, /批量移动/);
  assert.match(watchlistPageSource, /删除/);
  assert.match(watchlistPageSource, /saveWatchlistPool/);
  assert.match(watchlistPageSource, /addWatchlistPoolItem/);
  assert.match(stockPageSource, /getStockKline/);
  assert.match(stockPageSource, /getStockResearch/);
  assert.match(stockPageSource, /StockResearchResponse/);
  assert.match(stockPageSource, /KLineChart/);
  assert.match(stockPageSource, /StockListPanel/);
  assert.match(stockPageSource, /行情摘要/);
  assert.match(stockPageSource, /股票列表/);
  assert.match(stockPageSource, /日 K 线/);
  assert.match(stockPageSource, /VolumeChart/);
  assert.match(stockPageSource, /KdjChart/);
  assert.match(stockPageSource, /pointCount = values\.length/);
  assert.match(stockPageSource, /kdjPoints\.length/);
  assert.doesNotMatch(stockPageSource, /MomentumChart/);
  assert.doesNotMatch(stockPageSource, /buildMomentumPoints/);
  assert.doesNotMatch(stockPageSource, /动量/);
  assert.doesNotMatch(stockPageSource, /FAST:/);
  assert.doesNotMatch(stockPageSource, /SLOW:/);
  assert.match(stockPageSource, /const CHART_WIDTH = 1120/);
  assert.match(stockPageSource, /const PRICE_CHART_HEIGHT = 560/);
  assert.match(stockPageSource, /const INDICATOR_CHART_HEIGHT = 126/);
  assert.match(stockPageSource, /PRICE_CHART_HEIGHT_CLASS/);
  assert.match(stockPageSource, /INDICATOR_CHART_HEIGHT_CLASS/);
  assert.match(stockPageSource, /clamp\(360px,56vh,560px\)/);
  assert.match(stockPageSource, /clamp\(88px,13vh,126px\)/);
  assert.match(stockPageSource, /preserveAspectRatio="none"/);
  assert.doesNotMatch(stockPageSource, /data\.source_status\.detail/);
  assert.match(stockPageSource, /KlineZoomControl/);
  assert.match(stockPageSource, /min-h-\[34px\]/);
  assert.match(stockPageSource, /min-w-\[34px\]/);
  assert.match(stockPageSource, /MovingAverageControl/);
  assert.match(stockPageSource, /type MovingAverageField = "ma5" \| "ma10" \| "ma20" \| "ma60"/);
  assert.match(stockPageSource, /visibleMovingAverages/);
  assert.match(stockPageSource, /MA60/);
  assert.match(stockPageSource, /activeChartTab/);
  assert.match(stockPageSource, /overflow-x-auto border-b border-slate-200 bg-slate-50/);
  assert.match(stockPageSource, /grid min-w-\[520px\] grid-cols-6/);
  assert.match(stockPageSource, /focus-visible:outline-none focus-visible:ring-2/);
  assert.match(stockPageSource, /研究/);
  assert.match(stockPageSource, /iFinD 研究/);
  assert.match(stockPageSource, /行业研究/);
  assert.match(stockPageSource, /财务指标/);
  assert.match(stockPageSource, /估值指标/);
  assert.match(stockPageSource, /风险事件/);
  assert.match(stockPageSource, /公司公告/);
  assert.match(stockPageSource, /新闻资讯/);
  assert.doesNotMatch(stockPageSource, /财务估值/);
  assert.doesNotMatch(stockPageSource, /公告新闻/);
  assert.doesNotMatch(stockPageSource, /title="板块强度"/);
  assert.match(stockPageSource, /setActiveChartTab/);
  assert.match(stockPageSource, /buildMovingAverageBars/);
  assert.match(stockPageSource, /buildWeeklyBars/);
  assert.match(stockPageSource, /chartWindowSize/);
  assert.match(stockPageSource, /onWheel/);
  assert.match(stockPageSource, /visibleBars/);
  assert.doesNotMatch(stockPageSource, /返回 \{bars\.length\} 条日K/);
  assert.doesNotMatch(stockPageSource, /xl:min-w-\[980px\]/);
  assert.doesNotMatch(stockPageSource, /xl:grid-cols-\[minmax\(0,1fr\)_270px\]/);
  assert.doesNotMatch(stockPageSource, /h-\[500px\]/);
  assert.doesNotMatch(watchlistPageSource, /盘中监控/);
  assert.doesNotMatch(componentSource + pageSource, /报告生成|历史报告|OCR|定时生成/);
  assert.match(settingsPageSource, /iFinD 研究增强/);
  assert.match(settingsPageSource, /ifind_api_key/);
  assert.match(settingsPageSource, /ifind_base_url/);
  assert.match(settingsPageSource, /hexin-ifind-ds-stock-mcp/);
  assert.match(settingsPageSource, /不替代 TickFlow 行情/);
});
